import { type BkAgentRespInfo, type ChargeInfo, type EnterprisePayInfo, type FulfillmentDetail, type TradeFundBill, type HbFqPayInfo, type IntactChargeInfo, type PaymentInfoWithId, type GoodsDetail, type TapPayInfo, type TradeSettleInfo, type VoucherDetail } from "@/interface";

export interface AlipayTradeQueryResponse {
    code?: string;
    msg?: string;
    subCode?: string;
    subMsg?: string;
    body?: string;
    params?: AlipayTradeQueryResponseParams;
    additionalStatus?: string;
    alipayStoreId?: string;
    alipaySubMerchantId?: string;
    asyncPayApplyStatus?: string;
    authTradePayMode?: string;
    bizSettleMode?: string;
    bkagentRespInfo?: BkAgentRespInfo;
    buyerLogonId?: string;
    buyerOpenId?: string;
    buyerPayAmount?: string;
    buyerUserId?: string;
    buyerUserName?: string;
    buyerUserType?: string;
    cashierType?: string;
    chargeAmount?: string;
    chargeFlags?: string;
    chargeInfoList?: ChargeInfo[];
    creditBizOrderId?: string;
    creditPayMode?: string;
    discountAmount?: string;
    discountGoodsDetail?: string;
    enterprisePayInfo?: EnterprisePayInfo;
    extInfos?: string;
    fulfillmentDetailList?: FulfillmentDetail[];
    fundBillList?: TradeFundBill[];
    hbFqPayInfo?: HbFqPayInfo;
    hybAmount?: string;
    industrySepcDetail?: string;
    industrySepcDetailAcc?: string;
    industrySepcDetailGov?: string;
    intactChargeInfoList?: IntactChargeInfo[];
    invoiceAmount?: string;
    mdiscountAmount?: string;
    medicalInsuranceInfo?: string;
    openId?: string;
    outTradeNo?: string;
    passbackParams?: string;
    payAmount?: string;
    payCurrency?: string;
    paymentInfoWithIdList?: PaymentInfoWithId[];
    periodScene?: string;
    pointAmount?: string;
    preAuthPayAmount?: string;
    receiptAmount?: string;
    receiptCurrencyType?: string;
    reqGoodsDetail?: GoodsDetail[];
    sendPayDate?: string;
    settleAmount?: string;
    settleCurrency?: string;
    settleTransRate?: string;
    settlementId?: string;
    storeId?: string;
    storeName?: string;
    subject?: string;
    tapPayInfo?: TapPayInfo;
    terminalId?: string;
    totalAmount?: string;
    tradeNo?: string;
    tradeSettleInfo?: TradeSettleInfo;
    tradeStatus?: string;
    transCurrency?: string;
    transPayRate?: string;
    voucherDetailList?: VoucherDetail[];
    errorCode?: string;
    success?: boolean;
}

export interface AlipayTradeQueryResponseParams {
    [key: string]: any;
}
